version: "3.8"

services:
  api-gateway:
    build: ../services/api-gateway
    container_name: api-gateway
    ports:
      - "4000:4000"

  ingestion:
    build: ../services/ingestion
    container_name: ingestion
    ports:
      - "4001:4001"

  decision:
    build: ../services/decision
    container_name: decision
    ports:
      - "4002:4002"
